### ISSUE TITLE
Not render css

### ISSUE THREAD

**Issue by hfcipriano** [moodysalem/java-phantomjs-wrapper#11]
On invocation:

```
PhantomJS.render(null,
                new URL("http://www.myUrl.com").openStream(),
                PaperSize.A4, ViewportDimensions.VIEW_1280_1024,
                Margin.ZERO, BannerInfo.EMPTY, BannerInfo.EMPTY, RenderFormat.PDF, 10000L, 100L);
```

The html is rendered but without css.

What i'm doing wrong?

**Comment by moodysalem** [comment]
I don't know why I missed this, but my guess is that the user agent failed to fetch the CSS files, or the CSS is injected into the HTML after the initial request completes and the markup is rendered. I haven't had any issue with inline styles or styles coming from stylesheets embedded in the html page.

Let me know if you have any more diagnostic information
