### ISSUE TITLE
not render javascript files

### ISSUE THREAD

**Issue by surifirstpin** [moodysalem/java-phantomjs-wrapper#12]
hi ... javascript files are not loaded in java-phantomjs wrapper.please tell me how to include js files. it has taken <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script> like this.But it does not take <script src="jquery-3.3.3"></script>.How can i fix this .

**Comment by moodysalem** [comment]
I'm not sure why this wouldn't work, please provide the URL you are trying to render and the logs
